//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "65bec669fcfda844da82882d"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test Testsson25",
  "email": "test25@mail.com",
  "password": "test"
}

###

// LOGGA IN USER // VID FEL LÖSENORD SÅ SKALL SVARA MED 401
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "test1"
}

###

//
// API ENDPOINTS PRODUCTS
//

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/65be4f366999f1b2d3927d29

###

// SKAPA PRODUKT // UTAN TOKEN SÅ SKALL ANROPET MISSLYCKAS = 401
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Här är teste",
  "description": "Beskrivning av produkt 30",
  "price": 300,
  "lager": 330,
  "category": "65c153753c16763ec497ed7b",
  "token": "1234key1234"
  
}

###

// HÄMTA ALLA PRODUKTER FÖR EN SPECIFIK KATEGORI
GET http://localhost:3000/api/products/category/65bf95f8ab8ac299af37bbe8
###

//
// API ENDPOINTS KATEGORI
// 

// SKAPA KATEGORI, KEY MÅSTE ANGES // UTAN KEY SVARA 401
# @name createCategory
POST http://localhost:3000/api/categories/add
Content-Type: application/json

{
  "name": "Kategori 100",
  "token": "1234key1234"
}

###

# @name getCategories
GET http://localhost:3000/api/categories

###

//
// API ENDPOINTS ORDERS
//

// HÄMTA ALLA ORDERS, KEY MÅSTE ANGES FÖR ATT FÅ TILLGÅNG TILL ORDERS
GET http://localhost:3000/api/orders/all/secretKey1

###

// HÄMTA ALLA ORDER, FEL KEY // SKALL MISSLYCKAS
GET http://localhost:3000/api/orders/all/test1

###

// SKAPA ORDER FÖR EN SPECIFIK USER
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "65bfa2e0219c26725f880cf8",
      "products": [
    {
      "productId": "65bfe9d389a04c6f46e467f6",
      "quantity": 1
    },
    {
      "productId": "65bfebbbd640abbdcb898aeb",
      "quantity": 2
    }
  ]
}

###

// HÄMTA ORDERS FÖR EN USER // SKALL MISSLYCKAS = INGEN KEY  // SVARA MED 401
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "65bfa2e0219c26725f880cf8"
}
###

// HÄMTA ORDERS FÖR EN USER // SKALL LYCKAS = KEY
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "65bfa2e0219c26725f880cf8",
    "token": "1234key1234"
}
###