//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "65bd727d277bce119e040cc0"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test6",
  "email": "test6@mail.com",
  "password": "test6"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test3@mail.com",
  "password": "test3"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/65be4f366999f1b2d3927d29

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 4",
  "description": "Beskrivning av produkt 4",
  "price": 400, 
  "lager": 40
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "65be4a113c4217b27382381d",
      "products": [
    {
      "productId": "65be4f15fd6804117d506efc",
      "quantity": 1
    },
    {
      "productId": "65be4ed755b994003e151481",
      "quantity": 2
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###

POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "65bd6be0e4c00a7eff4a8b93",
      "products": [    
    {
      "productId": "65be4f366999f1b2d3927d29"
    },
    {
      "productId": "65be4f296999f1b2d3927d27"
    }]
}

###