//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "65bd727d277bce119e040cc0"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test7",
  "email": "test7@mail.com",
  "password": "test7"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test3@mail.com",
  "password": "test3"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/65be4f366999f1b2d3927d29

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 5",
  "description": "Beskrivning av produkt 5",
  "price": 500, 
  "lager": 50
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "65be4a113c4217b27382381d",
      "products": [
    {
      "productId": "65be4ef5fd6804117d506ef8",
      "quantity": 20
    },
    {
      "productId": "65be4ef7fd6804117d506efa",
      "quantity": 20
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###

